import 'dart:convert';
import 'package:file_selector/file_selector.dart';
import 'package:flutter/material.dart';
import '../core/app_controller.dart';
import '../core/json.dart';
import '../widgets/common.dart';

class FileStorageScreen extends StatefulWidget { const FileStorageScreen({required this.name, super.key}); final String name; @override State<FileStorageScreen> createState()=>_FileStorageScreenState(); }
class _FileStorageScreenState extends State<FileStorageScreen>{ List<JsonMap>? objects; String prefix=''; String? error; bool busy=true;
 @override void initState(){super.initState();_load();}
 Future<void> _load() async {setState(()=>busy=true);try{final d=await AppScope.of(context,listen:false).invoke('listStorageObjects',[widget.name,prefix]);if(mounted)setState(()=>objects=jsonList(d));}catch(e){if(mounted)setState(()=>error=e.toString());}finally{if(mounted)setState(()=>busy=false);}}
 Future<void> _upload() async {final f=await openFile(); if(f==null)return; final bytes=await f.readAsBytes(); final name='$prefix${f.name}'; try{await AppScope.of(context,listen:false).invoke('uploadStorageObject',[widget.name,name,base64Encode(bytes)]);_load();}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}}
 Future<void> _newFolder() async {final c=TextEditingController(); final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('新建文件夹'),content:TextField(controller:c,autofocus:true,decoration:const InputDecoration(hintText:'文件夹名称')),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('取消')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('创建'))])); if(ok==true&&c.text.trim().isNotEmpty){await AppScope.of(context,listen:false).invoke('createStorageFolder',[widget.name,'$prefix${c.text.trim()}']);_load();}}
 Future<void> _delete(String n) async {final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('删除文件'),content:Text('确定删除 $n？'),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('取消')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('删除'))]));if(ok==true){await AppScope.of(context,listen:false).invoke('deleteStorageObject',[widget.name,n]);_load();}}
 @override Widget build(BuildContext c)=>Column(children:[Padding(padding:const EdgeInsets.fromLTRB(24,12,24,10),child:Row(children:[IconButton(tooltip:'返回',onPressed:()=>AppScope.of(c,listen:false).closeDetail(),icon:const Icon(Icons.arrow_back,size:19)),const SizedBox(width:8),Text('文件存储',style:Theme.of(c).textTheme.titleLarge),const SizedBox(width:10),Text(widget.name),const Spacer(),IconButton(tooltip:'新建文件夹',onPressed:_newFolder,icon:const Icon(Icons.create_new_folder_outlined,size:19)),IconButton(tooltip:'上传文件',onPressed:_upload,icon:const Icon(Icons.upload_file_outlined,size:19)),IconButton(tooltip:'刷新',onPressed:busy?null:_load,icon:const Icon(Icons.refresh,size:19))])),
 if(prefix.isNotEmpty) Align(alignment:Alignment.centerLeft,child:TextButton.icon(onPressed:(){setState(()=>prefix='');_load();},icon:const Icon(Icons.home_outlined,size:17),label:Text('/ $prefix'))),
 Expanded(child:busy?const BrandLoading():error!=null?ErrorBanner(message:error!):objects!.isEmpty?const EmptyState(icon:Icons.folder_open_outlined,title:'暂无文件'):ListView.separated(padding:const EdgeInsets.fromLTRB(24,4,24,24),itemCount:objects!.length,separatorBuilder:(_,_)=>const Divider(height:1),itemBuilder:(c,i){final o=objects![i];final n=stringValue(o['name']);final folder=n.endsWith('/');return ListTile(leading:Icon(folder?Icons.folder_outlined:Icons.insert_drive_file_outlined),title:Text(n.substring(prefix.length)),subtitle:folder?null:Text('${intValue(o['size'])} bytes'),dense:true,onTap:folder?(){setState(()=>prefix=n);_load();}:null,trailing:IconButton(tooltip:'删除',onPressed:()=>_delete(n),icon:const Icon(Icons.delete_outline,size:18)));}))]); }
